import type { ContentManifest, FortuneTemplate } from './schema.js';

const contentVersion = 'phase2-slice-2026-08-05';

function reading(
  cardKey: string,
  orientation: FortuneTemplate['orientation'],
  intention: FortuneTemplate['intention'],
  headline: string,
  message: string,
  action: string,
  affirmation: string,
): FortuneTemplate {
  return {
    cardKey,
    locale: 'en',
    orientation,
    intention,
    variant: 1,
    headline,
    message,
    action,
    affirmation,
    contentVersion,
    editorialStatus: 'READY_FOR_REVIEW',
    active: true,
  };
}

export const developmentContentManifest = {
  schemaVersion: 1,
  contentVersion,
  locales: ['en'],
  cards: [
    {
      key: 'major-00-fool',
      displayNumber: '0',
      arcana: 'MAJOR',
      sliceRole: 'MAJOR',
      assetKey: 'major-00-fool',
      localizedName: { en: 'The Fool' },
      localizedAltText: {
        en: 'A traveler at a cliff lifts a white flower while a small dog watches beneath a radiant dawn star.',
      },
      localizedIllustrationDescription: {
        en: 'A curious traveler and small white dog pause at a flowered cliff as a golden dawn star opens the indigo sky.',
      },
      editorialStatus: 'READY_FOR_REVIEW',
      sortOrder: 0,
      active: true,
    },
    {
      key: 'cups-queen',
      displayNumber: 'Q',
      arcana: 'MINOR',
      sliceRole: 'COURT',
      suit: 'CUPS',
      rank: 'QUEEN',
      assetKey: 'cups-queen',
      localizedName: { en: 'Queen of Cups' },
      localizedAltText: {
        en: 'A crowned queen holds an ornate silver cup beside calm water, white lilies, and a crescent moon.',
      },
      localizedIllustrationDescription: {
        en: 'A composed queen cradles an ornate silver cup among white lilies beside moonlit teal water and a slim crescent moon.',
      },
      editorialStatus: 'READY_FOR_REVIEW',
      sortOrder: 48,
      active: true,
    },
    {
      key: 'wands-03',
      displayNumber: 'III',
      arcana: 'MINOR',
      sliceRole: 'PIP',
      suit: 'WANDS',
      rank: 'THREE',
      assetKey: 'wands-03',
      localizedName: { en: 'Three of Wands' },
      localizedAltText: {
        en: 'A cloaked figure stands with three flowering staffs above a luminous sea dotted with distant ships.',
      },
      localizedIllustrationDescription: {
        en: 'A cloaked figure surveys distant silver ships from a high shore, framed by three flowering staffs beneath an expansive violet sky.',
      },
      editorialStatus: 'READY_FOR_REVIEW',
      sortOrder: 24,
      active: true,
    },
  ],
  templates: [
    reading(
      'major-00-fool',
      'UPRIGHT',
      'GENERAL',
      'Fresh ground welcomes a first step',
      'A beginning may be asking for attention before every detail is settled. The Fool invites curiosity, preparation without paralysis, and a willingness to learn from one honest step. Notice where uncertainty has become a reason to stay still. You do not need to promise an outcome; you may simply make enough room for discovery to meet you.',
      'Choose one small beginning and give it ten attentive minutes today.',
      'I can meet the unknown with curiosity.',
    ),
    reading(
      'major-00-fool',
      'UPRIGHT',
      'LOVE',
      'Let warmth unfold at an honest pace',
      'The Fool may bring fresh air to the way you approach connection. Openness matters, and so does staying present to what another person actually shares. Consider where old expectations are writing the story too early. A lighter stance can make room for play, candid questions, and boundaries that let trust develop without asking either person to rush.',
      'Share one sincere curiosity, then listen without planning the other person’s answer.',
      'I welcome connection without abandoning my pace.',
    ),
    reading(
      'major-00-fool',
      'UPRIGHT',
      'WORK',
      'Treat the next move as an experiment',
      'A new task or direction may feel larger because you are measuring it against a finished result. The Fool invites a useful experiment instead. Notice which assumption could be tested with a modest, reversible step. Curiosity can reveal information that planning alone cannot provide, while a clear limit keeps the exploration grounded and respectful of your existing responsibilities.',
      'Define one reversible work experiment with a clear limit and learning question.',
      'I learn by taking thoughtful first steps.',
    ),
    reading(
      'major-00-fool',
      'UPRIGHT',
      'GROWTH',
      'Beginner’s eyes reveal another path',
      'Growth may arrive through becoming teachable again. The Fool invites you to loosen the need to appear fully prepared and notice what genuine interest keeps returning. This is not a command to discard experience; it is permission to let experience serve exploration. A humble beginning can reconnect effort with wonder and make the next lesson easier to recognize.',
      'Approach one familiar practice as a beginner and record what surprises you.',
      'Curiosity keeps my growth alive.',
    ),
    reading(
      'major-00-fool',
      'REVERSED',
      'GENERAL',
      'Pause long enough to see the edge',
      'The reversed Fool may reflect motion that is either hurried or repeatedly postponed. Notice which pattern is present without turning it into a verdict about yourself. A pause can separate healthy caution from fear, or excitement from impulse. Gather the one piece of information that would make your next step more considered, then reassess from steadier ground.',
      'Name the risk, the safeguard, and the smallest considered step available.',
      'I can pause without losing possibility.',
    ),
    reading(
      'major-00-fool',
      'REVERSED',
      'LOVE',
      'Clarity belongs beside chemistry',
      'Excitement or uncertainty may be making a connection difficult to read. The reversed Fool invites a slower look at words, actions, and the boundaries you need to feel present. Avoid filling silence with a preferred story. A direct, gentle question can offer more useful information than guessing, while leaving both people free to answer at their own pace.',
      'Ask one clear question about expectations and make space for an honest reply.',
      'I pair openness with clear boundaries.',
    ),
    reading(
      'major-00-fool',
      'REVERSED',
      'WORK',
      'Unstick the start with one safeguard',
      'A work beginning may be caught between overconfidence and overplanning. The reversed Fool asks what would make movement both useful and responsible. Consider the dependency, approval, or limit that has not yet been named. Once it is visible, a small test may replace vague pressure with evidence and help the wider plan become easier to discuss.',
      'Write the missing safeguard, then schedule one bounded test with its owner.',
      'Careful movement is still movement.',
    ),
    reading(
      'major-00-fool',
      'REVERSED',
      'GROWTH',
      'Meet hesitation without making it identity',
      'The reversed Fool may highlight an inner critic that treats uncertainty as proof you are unready. Notice the difference between needing preparation and demanding perfect confidence. Growth can include a compassionate pause, a request for support, or a smaller practice round. You are allowed to learn in view of your limits rather than waiting to become fearless.',
      'Describe your hesitation kindly and choose one low-stakes practice round.',
      'I am more than my hesitation.',
    ),
    reading(
      'cups-queen',
      'UPRIGHT',
      'GENERAL',
      'Listen closely without carrying everything',
      'The Queen of Cups invites attention to the feelings moving beneath a busy surface. Sensitivity can be informative without becoming an obligation to absorb every mood around you. Notice what belongs to your experience and what may belong to someone else. A calm boundary can protect the generous listening that helps you respond with care and proportion.',
      'Take three quiet breaths, name your feeling, and name what is not yours.',
      'My care can include clear boundaries.',
    ),
    reading(
      'cups-queen',
      'UPRIGHT',
      'LOVE',
      'Tender presence makes room for truth',
      'Connection may deepen through listening that is warm, specific, and unhurried. The Queen of Cups invites compassion without mind reading. Notice what has actually been expressed and where a gentle question could replace assumption. Caring for the relationship also includes naming your own needs, so empathy becomes a shared current instead of a one-sided act of emotional labor.',
      'Reflect back what you heard, then state one need in plain language.',
      'I offer tenderness and remain visible.',
    ),
    reading(
      'cups-queen',
      'UPRIGHT',
      'WORK',
      'Pair emotional insight with clear facts',
      'The Queen of Cups may point to the quiet information carried by tone, morale, and unspoken strain. Let that awareness guide a question rather than a conclusion. At work, empathy becomes most useful when paired with concrete facts, roles, and boundaries. Consider how a thoughtful check-in could surface what a plan or collaboration needs next.',
      'Ask one neutral check-in question and note the facts in the response.',
      'I bring empathy and clarity together.',
    ),
    reading(
      'cups-queen',
      'UPRIGHT',
      'GROWTH',
      'Intuition grows clearer beside evidence',
      'Your inner response may hold a useful signal, especially when you give it quiet space. The Queen of Cups invites you to receive that signal gently and then place it beside observable facts. This balance keeps intuition from becoming pressure. Notice which feeling repeats, what it may be protecting, and what additional information would help you understand it.',
      'Journal the recurring feeling, the facts beside it, and one open question.',
      'I listen inward and stay grounded.',
    ),
    reading(
      'cups-queen',
      'REVERSED',
      'GENERAL',
      'Your inner cup may need replenishing',
      'The reversed Queen of Cups may reflect emotional saturation, porous boundaries, or care that has outrun available energy. Notice the earliest sign that you are becoming depleted. A smaller promise, a quiet interval, or a request for help can restore proportion. Rest is not a failure of compassion; it can help compassion remain sincere and sustainable.',
      'Reduce one optional demand and reserve a quiet interval for yourself.',
      'My needs deserve attentive care.',
    ),
    reading(
      'cups-queen',
      'REVERSED',
      'LOVE',
      'Care does not require self-erasure',
      'You may be giving more emotional attention than you can renew, or waiting for unspoken needs to be noticed. The reversed Queen of Cups invites honest limits and direct language. Consider whether rescuing, guessing, or smoothing every discomfort has crowded out mutuality. A caring boundary can reveal whether the connection has room for both people’s experience.',
      'Name one need directly and release responsibility for managing the entire response.',
      'I remain whole while I care.',
    ),
    reading(
      'cups-queen',
      'REVERSED',
      'WORK',
      'Separate the room’s mood from your role',
      'The reversed Queen of Cups may appear when workplace emotion is difficult to filter. Sensitivity can register tension before the facts are clear, but it need not assign you the job of fixing everything. Notice your actual responsibility, document what is observable, and choose a measured conversation or pause. Boundaries can preserve both kindness and professional judgment.',
      'List the observable facts, your responsibility, and one boundary for today.',
      'I can care without absorbing the room.',
    ),
    reading(
      'cups-queen',
      'REVERSED',
      'GROWTH',
      'Turn compassion gently toward yourself',
      'The reversed Queen of Cups invites inward listening when self-criticism has become louder than useful reflection. Notice whether you offer others patience that you deny yourself. A kinder internal voice does not avoid accountability; it creates enough safety to learn from what happened. Consider the response you would offer a trusted friend facing the same imperfect moment.',
      'Write yourself three compassionate sentences that still acknowledge the lesson.',
      'I can be accountable and kind.',
    ),
    reading(
      'wands-03',
      'UPRIGHT',
      'GENERAL',
      'The horizon widens through considered reach',
      'The Three of Wands may signal a moment to look beyond the immediate shoreline. Something already begun can benefit from wider perspective, patient outreach, or a clearer view of what comes next. Notice which possibility has enough foundation to explore. Expansion does not require chasing every option; it invites choosing a direction and watching the conditions carefully.',
      'Map three possible next steps and circle the one with firm foundations.',
      'I expand with patience and purpose.',
    ),
    reading(
      'wands-03',
      'UPRIGHT',
      'LOVE',
      'A shared horizon needs shared words',
      'The Three of Wands invites conversation about the direction a connection may take. Hope can be energizing, yet assumptions about timing or commitment can leave people viewing different horizons. Notice what future question feels ready for respectful discussion. Speak from your own wishes, stay curious about the other view, and allow alignment to emerge through clarity rather than pressure.',
      'Share one future hope as a possibility and invite the other perspective.',
      'I meet shared plans with honest curiosity.',
    ),
    reading(
      'wands-03',
      'UPRIGHT',
      'WORK',
      'Build the bridge beyond current reach',
      'Work already underway may be ready for a broader audience, partner, or next stage. The Three of Wands invites strategic outreach supported by preparation. Notice which result, prototype, or lesson is solid enough to share. A concise message and a clear request can open useful dialogue while keeping expectations proportionate to the evidence you have.',
      'Choose one relevant person and send a concise, specific invitation to connect.',
      'I extend my work with intention.',
    ),
    reading(
      'wands-03',
      'UPRIGHT',
      'GROWTH',
      'Perspective reveals the distance already crossed',
      'The Three of Wands may invite you to step back and view your development across a longer span. Daily effort can hide meaningful movement when attention stays fixed on what remains. Notice a capacity that has become steadier through practice. Let that evidence inform the next horizon, balancing ambition with appreciation for the ground already covered.',
      'Record one past milestone, one present strength, and one emerging horizon.',
      'I honor progress while looking forward.',
    ),
    reading(
      'wands-03',
      'REVERSED',
      'GENERAL',
      'A delayed horizon can refine the route',
      'The reversed Three of Wands may reflect plans meeting distance, delay, or a narrower opening than expected. This does not make the original effort meaningless. Notice which condition has changed and which part remains within your influence. Adjusting the route, timing, or scale can preserve the purpose while releasing attachment to one exact form.',
      'Identify the changed condition and revise one assumption in your plan.',
      'I can adapt without abandoning purpose.',
    ),
    reading(
      'wands-03',
      'REVERSED',
      'LOVE',
      'Bring distant expectations into the room',
      'A connection may be carrying different expectations about pace, distance, or the future. The reversed Three of Wands invites those differences into a present, respectful conversation. Notice where you have been relying on hints or private timelines. Clear language can reduce uncertainty, even when the answer is still developing, and gives each person room to choose thoughtfully.',
      'Ask how each of you sees the next season, without demanding certainty.',
      'I welcome clarity at a humane pace.',
    ),
    reading(
      'wands-03',
      'REVERSED',
      'WORK',
      'Find the bottleneck before pushing harder',
      'The reversed Three of Wands may point to expansion slowed by an unseen dependency, unclear ownership, or limited capacity. More effort alone may not resolve the constraint. Notice where work repeatedly waits, returns, or loses context. Naming the bottleneck with the people involved can turn diffuse frustration into a smaller operational question that is easier to address.',
      'Trace one delayed task backward and name its first unresolved dependency.',
      'I seek clarity before adding effort.',
    ),
    reading(
      'wands-03',
      'REVERSED',
      'GROWTH',
      'Comparison can obscure your own horizon',
      'The reversed Three of Wands may highlight attention fixed on someone else’s distance or pace. Comparison can offer information, but it becomes heavy when used as a verdict. Notice what you actually admire and translate it into a skill, practice, or value relevant to your path. Your next horizon can be specific without needing to resemble another person’s map.',
      'Turn one comparison into a personal value and a modest practice.',
      'My path can have its own horizon.',
    ),
  ],
} satisfies ContentManifest;
